#pragma once

#include <array>
#include <cassert>
#include <cmath>
#include <functional>
#include <iostream>
#include <string>
#include <vector>

#include "types.hpp"
#include "utils.hpp"


namespace Sift {

class Tunable {
public:
    using Callback = std::function<void()>;

    Tunable() : name_(), value_(), min_(), max_(), step_(), callback_() {}
    Tunable(const std::string &name, Int32 value, Int32 min, Int32 max, Int32 step, Callback callback);

    constexpr explicit operator std::string() const { return name_ + ", int, " + std::to_string(value_) + ", " + std::to_string(min_) + ", " + std::to_string(max_) + ", " + std::to_string(step_) + ", " + LEARNING_RATE; }

    const std::string &name() const noexcept { return name_; }
    constexpr Int32 &value() noexcept { return value_; }
    constexpr Int32 min() const noexcept { return min_; }
    constexpr Int32 max() const noexcept { return max_; }
    constexpr Int32 step() const noexcept { return step_; }
    Callback callback() const noexcept { return callback_; }

    constexpr void update(Int32 value) noexcept {
        if (value < min_) {
            value = min_;
        } else if (value > max_) {
            value = max_;
        }
        value_ = value;
        callback_();
    }

private:
    static constexpr std::string LEARNING_RATE = "0.002";

    std::string name_;
    Int32 value_;
    Int32 min_;
    Int32 max_;
    Int32 step_;
    Callback callback_;
};

class TunableList {
public:
    constexpr TunableList() noexcept : tunables_() {}

    static void init() noexcept;

    constexpr std::vector<Tunable>::iterator begin() noexcept { return tunables_.begin(); }
    constexpr std::vector<Tunable>::const_iterator begin() const noexcept { return tunables_.begin(); }
    constexpr std::vector<Tunable>::iterator end() noexcept { return tunables_.end(); }
    constexpr std::vector<Tunable>::const_iterator end() const noexcept { return tunables_.end(); }

    void add(const Tunable &tunable) { tunables_.push_back(tunable); }

    void update(const std::string &name, Int32 value) {
        for (Tunable &tunable : tunables_) {
            if (tunable.name() == name) {
                tunable.update(value);
                break;
            }
        }
    }

    void openBenchConfig() const noexcept {
        for (const Tunable &tunable : tunables_) {
            std::cout << std::string(tunable) << std::endl;
        }
    }

private:
    std::vector<Tunable> tunables_;
};

inline TunableList TUNABLES;

inline Tunable::Tunable(const std::string &name, Int32 value, Int32 min, Int32 max, Int32 step, Callback callback) : name_(name), value_(value), min_(min), max_(max), step_(step), callback_(std::move(callback)) { TUNABLES.add(*this); }

#if defined(OPEN_BENCH_TUNE)
#define TUNABLE_CALLBACK(name, val, min, max, step, callback) \
    inline Tunable name##_TUNABLE = Tunable(#name, val, min, max, step, callback); \
    inline Int32 &name = name##_TUNABLE.value();
#else
#define TUNABLE_CALLBACK(name, val, min, max, step, callback) \
    static constexpr Int32 name = val;
#endif

#define TUNABLE(name, val, min, max, step) \
    TUNABLE_CALLBACK(name, val, min, max, step, []() {})


static constexpr Int32 FDEPTH_SCALE = 128;

TUNABLE(TT_REPLACE_DEPTH_OFFSET, 512, 0, 0, 0);
TUNABLE(TT_REPLACE_PV_SCALE, 256, 0, 0, 0);
TUNABLE(TT_QUALITY_FDEPTH_SCALE, 128, 0, 0, 0);
TUNABLE(TT_QUALITY_AGE_DIFF_SCALE, 256, 0, 0, 0);

static inline std::array<Int32, 7> MVV_PIECE_VALUES;

namespace MVV {

static void init();

}

TUNABLE_CALLBACK(MVV_PAWN_VALUE, 964, 0, 0, 0, []() { MVV::init(); });
TUNABLE_CALLBACK(MVV_KNIGHT_VALUE, 2465, 0, 0, 0, []() { MVV::init(); });
TUNABLE_CALLBACK(MVV_BISHOP_VALUE, 2360, 0, 0, 0, []() { MVV::init(); });
TUNABLE_CALLBACK(MVV_ROOK_VALUE, 4725, 0, 0, 0, []() { MVV::init(); });
TUNABLE_CALLBACK(MVV_QUEEN_VALUE, 7181, 0, 0, 0, []() { MVV::init(); });

static inline void MVV::init() { MVV_PIECE_VALUES = {MVV_PAWN_VALUE, MVV_KNIGHT_VALUE, MVV_BISHOP_VALUE, MVV_ROOK_VALUE, MVV_QUEEN_VALUE, 0, 0}; }

static inline std::array<Int32, 7> SEE_PIECE_VALUES;

namespace SEE {

static void init();

}

TUNABLE_CALLBACK(SEE_PAWN_VALUE, 97, 0, 0, 0, []() { SEE::init(); });
TUNABLE_CALLBACK(SEE_KNIGHT_VALUE, 434, 0, 0, 0, []() { SEE::init(); });
TUNABLE_CALLBACK(SEE_BISHOP_VALUE, 464, 0, 0, 0, []() { SEE::init(); });
TUNABLE_CALLBACK(SEE_ROOK_VALUE, 646, 0, 0, 0, []() { SEE::init(); });
TUNABLE_CALLBACK(SEE_QUEEN_VALUE, 1289, 0, 0, 0, []() { SEE::init(); });

static inline void SEE::init() { SEE_PIECE_VALUES = {SEE_PAWN_VALUE, SEE_KNIGHT_VALUE, SEE_BISHOP_VALUE, SEE_ROOK_VALUE, SEE_QUEEN_VALUE, 0, 0}; }

TUNABLE(TIME_BASE_TIME_SCALE, 19, 0, 0, 0);
TUNABLE(TIME_BASE_TIME_INCREMENT_SCALE, 83, 0, 0, 0);

TUNABLE(TIME_SOFT_BOUND_SCALE, 68, 0, 0, 0);
TUNABLE(TIME_HARD_BOUND_SCALE, 56, 0, 0, 0);

TUNABLE(TIME_SCALE_MATE_SCORE, 15, 0, 0, 0);
TUNABLE(TIME_SCALE_WIN_SCORE, 60, 0, 0, 0);
TUNABLE(TIME_SCALE_LOSS_SCORE, 50, 0, 0, 0);
TUNABLE(TIME_SCALE_NODE_BASE, 263, 0, 0, 0);
TUNABLE(TIME_SCALE_NODE_SCALE, 170, 0, 0, 0);
TUNABLE(TIME_SCALE_NODE_MIN, 10, 0, 0, 0);
TUNABLE(TIME_SCALE_STABILITY_BASE, 75, 0, 0, 0);
TUNABLE(TIME_SCALE_STABILITY_MAX, 240, 0, 0, 0);
TUNABLE(TIME_SCALE_STABILITY_SCALE, 911, 0, 0, 0);
TUNABLE(TIME_SCALE_STABILITY_OFFSET, 80, 0, 0, 0);
TUNABLE(TIME_SCALE_STABILITY_POWER, -270, 0, 0, 0);
TUNABLE(TIME_SCALE_SCORE_CHANGE_DIVISOR, 458, 0, 0, 0);
TUNABLE(TIME_SCALE_POS_SCORE_SCALE, 109, 0, 0, 0);
TUNABLE(TIME_SCALE_NEG_SCORE_SCALE, 104, 0, 0, 0);
TUNABLE(TIME_SCALE_SCORE_OFFSET, 80, 0, 0, 0);
TUNABLE(TIME_SCALE_SCORE_SCALE, 41, 0, 0, 0);
TUNABLE(TIME_SCALE_SCORE_MIN, 60, 0, 0, 0);
TUNABLE(TIME_SCALE_SCORE_MAX, 170, 0, 0, 0);
TUNABLE(TIME_SCALE_MIN, 7, 0, 0, 0);

static constexpr Int32 TIME_SCALE_STABILITY_MIN_DEPTH = 6;

TUNABLE(EVAL_ADJUST_PAWN_SCALE, 48, 0, 0, 0);
TUNABLE(EVAL_ADJUST_KNIGHT_SCALE, 435, 0, 0, 0);
TUNABLE(EVAL_ADJUST_BISHOP_SCALE, 455, 0, 0, 0);
TUNABLE(EVAL_ADJUST_ROOK_SCALE, 642, 0, 0, 0);
TUNABLE(EVAL_ADJUST_QUEEN_SCALE, 1217, 0, 0, 0);
TUNABLE(EVAL_ADJUST_MATERIAL_BASE, 26000, 0, 0, 0);
TUNABLE(EVAL_ADJUST_OPTIMISM_SCALE_BASE, 2024, 0, 0, 0);
TUNABLE(EVAL_ADJUST_OPTIMISM_SCALE_MATERIAL_SCALE, 1005, 0, 0, 0);
TUNABLE(EVAL_ADJUST_HALF_MOVE_SCALE, 200, 0, 0, 0);

TUNABLE(THREAD_WEIGHT_SCORE_OFFSET, 11, 0, 0, 0);

TUNABLE(MOVE_ORDER_GOOD_NOISY_MARGIN_SCORE_SCALE, 256, 0, 0, 0);
TUNABLE(MOVE_ORDER_GOOD_NOISY_MARGIN_OFFSET, 72, 0, 0, 0);
TUNABLE(MOVE_ORDER_NOISY_SCORE_SCALE, 128, 0, 0, 0);

TUNABLE(MOVE_ORDER_DIRECT_CHECK_BONUS, 5257, 0, 0, 0);
TUNABLE(MOVE_ORDER_DIRECT_CHECK_MARGIN, -37, 0, 0, 0);

TUNABLE(TT_CUTOFF_MAX_HALFMOVES, 90, 0, 0, 0);

TUNABLE(TT_CUTOFF_BONUS_DEPTH_SCALE, 263, 0, 0, 0);
TUNABLE(TT_CUTOFF_BONUS_OFFSET, 385, 0, 0, 0);
TUNABLE(TT_CUTOFF_BONUS_MAX, 2866, 0, 0, 0);

TUNABLE(EVAL_POLICY_BONUS_BASE, 503, 0, 0, 0);
TUNABLE(EVAL_POLICY_BONUS_GAIN_SCALE, 10, 0, 0, 0);
TUNABLE(EVAL_POLICY_BONUS_MIN, -1338, 0, 0, 0);
TUNABLE(EVAL_POLICY_BONUS_MAX, 2344, 0, 0, 0);

TUNABLE(POST_LMR_BONUS_DEPTH_SCALE, 277, 0, 0, 0);
TUNABLE(POST_LMR_BONUS_OFFSET, 575, 0, 0, 0);
TUNABLE(POST_LMR_BONUS_MAX, 2723, 0, 0, 0);

TUNABLE(POST_LMR_PENALTY_DEPTH_SCALE, 307, 0, 0, 0);
TUNABLE(POST_LMR_PENALTY_OFFSET, 245, 0, 0, 0);
TUNABLE(POST_LMR_PENALTY_MAX, 1027, 0, 0, 0);

TUNABLE(QUIET_BONUS_DEPTH_SCALE, 339, 0, 0, 0);
TUNABLE(QUIET_BONUS_OFFSET, 313, 0, 0, 0);
TUNABLE(QUIET_BONUS_MAX, 2663, 0, 0, 0);

TUNABLE(QUIET_PENALTY_DEPTH_SCALE, 384, 0, 0, 0);
TUNABLE(QUIET_PENALTY_OFFSET, 177, 0, 0, 0);
TUNABLE(QUIET_PENALTY_MAX, 1318, 0, 0, 0);

TUNABLE(NOISY_BONUS_DEPTH_SCALE, 274, 0, 0, 0);
TUNABLE(NOISY_BONUS_OFFSET, 469, 0, 0, 0);
TUNABLE(NOISY_BONUS_MAX, 2355, 0, 0, 0);

TUNABLE(QUIET_MOVE_NOISY_PENALTY_DEPTH_SCALE, 371, 0, 0, 0);
TUNABLE(QUIET_MOVE_NOISY_PENALTY_OFFSET, 78, 0, 0, 0);
TUNABLE(QUIET_MOVE_NOISY_PENALTY_MAX, 1629, 0, 0, 0);

TUNABLE(NOISY_MOVE_NOISY_PENALTY_DEPTH_SCALE, 319, 0, 0, 0);
TUNABLE(NOISY_MOVE_NOISY_PENALTY_OFFSET, 170, 0, 0, 0);
TUNABLE(NOISY_MOVE_NOISY_PENALTY_MAX, 1777, 0, 0, 0);

TUNABLE(PCM_QUIET_BONUS_DEPTH_SCALE, 132, 0, 0, 0);
TUNABLE(PCM_QUIET_BONUS_OFFSET, 58, 0, 0, 0);
TUNABLE(PCM_QUIET_BONUS_MAX, 1338, 0, 0, 0);

TUNABLE(PCM_NOISY_BONUS, 59, 0, 0, 0);

TUNABLE(HISTORY_FDEPTH_STATIC_EVAL_SCALE, 128, 0, 0, 0);

TUNABLE(MAIN_HIST_WEIGHT, 481, 0, 0, 0);
TUNABLE(PAWN_HIST_WEIGHT, 469, 0, 0, 0);
TUNABLE(CONT1_HIST_WEIGHT, 1082, 0, 0, 0);
TUNABLE(CONT2_HIST_WEIGHT, 1092, 0, 0, 0);
TUNABLE(CONT4_HIST_WEIGHT, 689, 0, 0, 0);
TUNABLE(CONT6_HIST_WEIGHT, 292, 0, 0, 0);
TUNABLE(CAPTURE_HIST_WEIGHT, 1024, 0, 0, 0);

TUNABLE(MAIN_HIST_UPDATE_WEIGHT, 975, 0, 0, 0);
TUNABLE(PAWN_HIST_UPDATE_WEIGHT, 891, 0, 0, 0);
TUNABLE(CONT1_HIST_UPDATE_WEIGHT, 1084, 0, 0, 0);
TUNABLE(CONT2_HIST_UPDATE_WEIGHT, 1142, 0, 0, 0);
TUNABLE(CONT4_HIST_UPDATE_WEIGHT, 952, 0, 0, 0);
TUNABLE(CONT6_HIST_UPDATE_WEIGHT, 1003, 0, 0, 0);
TUNABLE(CAPTURE_HIST_UPDATE_WEIGHT, 1024, 0, 0, 0);

TUNABLE(CONT_HIST_BASE_MAIN_HIST_WEIGHT, 211, 0, 0, 0);
TUNABLE(CONT_HIST_BASE_PAWN_HIST_WEIGHT, 101, 0, 0, 0);
TUNABLE(CONT_HIST_BASE_CONT1_HIST_WEIGHT, 929, 0, 0, 0);
TUNABLE(CONT_HIST_BASE_CONT2_HIST_WEIGHT, 917, 0, 0, 0);
TUNABLE(CONT_HIST_BASE_CONT4_HIST_WEIGHT, 553, 0, 0, 0);
TUNABLE(CONT_HIST_BASE_CONT6_HIST_WEIGHT, 320, 0, 0, 0);

TUNABLE(CORR_HIST_BONUS_FDEPTH_DIVISOR, 1024, 0, 0, 0);
TUNABLE(CORR_HIST_BONUS_MAX, 256, 0, 0, 0);
TUNABLE(CORR_HIST_PENALTY_MAX, 256, 0, 0, 0);

TUNABLE(PAWN_CORR_HIST_WEIGHT, 52, 0, 0, 0);
TUNABLE(FRIENDLY_NONPAWN_CORR_HIST_WEIGHT, 48, 0, 0, 0);
TUNABLE(ENEMY_NONPAWN_CORR_HIST_WEIGHT, 34, 0, 0, 0);
TUNABLE(MINOR_PIECE_CORR_HIST_WEIGHT, 33, 0, 0, 0);
TUNABLE(MAJOR_PIECE_CORR_HIST_WEIGHT, 51, 0, 0, 0);

TUNABLE(CONT1_CORR_HIST_WEIGHT, 71, 0, 0, 0);
TUNABLE(CONT2_CORR_HIST_WEIGHT, 66, 0, 0, 0);
TUNABLE(CONT4_CORR_HIST_WEIGHT, 44, 0, 0, 0);
TUNABLE(CONT6_CORR_HIST_WEIGHT, 30, 0, 0, 0);

TUNABLE(NOISY_MOVE_SEE_THRESHOLD_SCALE, 32, 0, 0, 0);

static constexpr Int32 WINDOW_MIN_DEPTH = 3;

TUNABLE(WINDOW_INIT_DELTA, 7, 0, 0, 0);
TUNABLE(WINDOW_SQUARED_SCORE_SCALE, 65, 0, 0, 0);
TUNABLE(WINDOW_FREDUCTION, 128, 0, 0, 0);
TUNABLE(WINDOW_MAX_FREDUCTION, 384, 0, 0, 0);
TUNABLE(WINDOW_WIDENING_SCALE, 136, 0, 0, 0);

static constexpr Int32 OPTIMISM_MIN_DEPTH = 2;

TUNABLE(OPTIMISM_SCORE_SCALE, 147, 0, 0, 0);
TUNABLE(OPTIMISM_DIVISOR_OFFSET, 101, 0, 0, 0);

TUNABLE(HINDSIGHT_FEXT_MIN_FREDUCTION, 384, 0, 0, 0);
TUNABLE(HINDSIGHT_FEXTENSION, 128, 0, 0, 0);
TUNABLE(HINDSIGHT_FRED_MIN_FDEPTH, 256, 0, 0, 0);
TUNABLE(HINDSIGHT_FRED_MIN_FREDUCTION, 256, 0, 0, 0);
TUNABLE(HINDSIGHT_FRED_MARGIN, 202, 0, 0, 0);
TUNABLE(HINDSIGHT_FREDUCTION, 128, 0, 0, 0);

TUNABLE(IIR_MIN_FDEPTH, 384, 0, 0, 0);
TUNABLE(IIR_TT_FDEPTH_OFFSET, 384, 0, 0, 0);
TUNABLE(IIR_FREDUCTION, 128, 0, 0, 0);

TUNABLE(RFP_MARGIN_LINEAR_DEPTH_SCALE, 36, 0, 0, 0);
TUNABLE(RFP_MARGIN_QUADRATIC_DEPTH_SCALE, 7, 0, 0, 0);
TUNABLE(RFP_MARGIN_IMPROVING_SCALE, 35, 0, 0, 0);
TUNABLE(RFP_MARGIN_COMPLEXITY_SCALE, 103, 0, 0, 0);
TUNABLE(RFP_MAX_FDEPTH, 1536, 0, 0, 0);
TUNABLE(RFP_FAIL_FIRM_T, 711, 0, 0, 0);

TUNABLE(RAZORING_MARGIN_DEPTH_SCALE, 234, 0, 0, 0);
TUNABLE(RAZORING_MAX_FDEPTH, 512, 0, 0, 0);
TUNABLE(RAZORING_FULL_ALWAYS_MAX_FDEPTH, 128, 0, 0, 0);
TUNABLE(RAZORING_FULL_MAX_FDEPTH, 256, 0, 0, 0);
TUNABLE(RAZORING_FULL_MARGIN, 173, 0, 0, 0);
TUNABLE(RAZORING_FRED_MAX_FDEPTH, 384, 0, 0, 0);
TUNABLE(RAZORING_FREDUCTION, 128, 0, 0, 0);

TUNABLE(NMP_MARGIN_BASE, 213, 0, 0, 0);
TUNABLE(NMP_MARGIN_DEPTH_SCALE, 1281, 0, 0, 0);
TUNABLE(NMP_MARGIN_IMPROVING_SCALE, 41, 0, 0, 0);
TUNABLE(NMP_MIN_FDEPTH, 512, 0, 0, 0);
TUNABLE(NMP_FRED_BASE, 424, 0, 0, 0);
TUNABLE(NMP_FRED_FDEPTH_SCALE, 200, 0, 0, 0);
TUNABLE(NMP_FRED_STATIC_EVAL_DIFF_SCALE, 82, 0, 0, 0);
TUNABLE(NMP_FRED_STATIC_EVAL_DIFF_MAX, 384, 0, 0, 0);
TUNABLE(NMP_NO_VERIF_MAX_DEPTH, 1920, 0, 0, 0);
TUNABLE(NMP_NO_VERIF_MARGIN, 25, 0, 0, 0);
TUNABLE(NMP_MIN_PLY_FDEPTH_SCALE, 96, 0, 0, 0);

TUNABLE(PROBCUT_BETA_OFFSET, 307, 0, 0, 0);
TUNABLE(PROBCUT_BETA_IMPROVING_SCALE, 10, 0, 0, 0);
TUNABLE(PROBCUT_FREDUCTION, 384, 0, 0, 0);
TUNABLE(PROBCUT_MIN_FDEPTH, 896, 0, 0, 0);
TUNABLE(PROBCUT_SEE_STATIC_EVAL_DIFF_SCALE, 136, 0, 0, 0);

TUNABLE(MINI_PROBCUT_BETA_OFFSET, 408, 0, 0, 0);
TUNABLE(MINI_PROBCUT_TT_FDEPTH_OFFSET, 384, 0, 0, 0);

TUNABLE(IIR2_MIN_FDEPTH, 256, 0, 0, 0);
TUNABLE(IIR2_FREDUCTION, 64, 0, 0, 0);

static inline MultiArray<Int32, 2, 256, 256> LMR_TABLE;

namespace LMR {

static void init();

}

TUNABLE_CALLBACK(LMR_NOISY_BASE, -10, 0, 0, 0, []() { LMR::init(); })
TUNABLE_CALLBACK(LMR_NOISY_DIVISOR, 249, 0, 0, 0, []() { LMR::init(); })
TUNABLE_CALLBACK(LMR_QUIET_BASE, 78, 0, 0, 0, []() { LMR::init(); })
TUNABLE_CALLBACK(LMR_QUIET_DIVISOR, 236, 0, 0, 0, []() { LMR::init(); })

static inline void LMR::init() {
    LMR_TABLE.fill({});

    const Float64 noisyBase = Utils::floatDiv100(LMR_NOISY_BASE);
    const Float64 noisyDivisor = Utils::floatDiv100(LMR_NOISY_DIVISOR);
    const Float64 quietBase = Utils::floatDiv100(LMR_QUIET_BASE);
    const Float64 quietDivisor = Utils::floatDiv100(LMR_QUIET_DIVISOR);

    for (Int32 depth = 1; depth < 256; depth++) {
        for (Int32 moves = 1; moves < 256; moves++) {
            const Float64 lnDepth = std::log(static_cast<Float64>(depth));
            const Float64 lnMoves = std::log(static_cast<Float64>(moves));
            LMR_TABLE[0][static_cast<USize>(depth)][static_cast<USize>(moves)] = static_cast<Int32>(1024.0 * (noisyBase + lnDepth * lnMoves / noisyDivisor));
            LMR_TABLE[1][static_cast<USize>(depth)][static_cast<USize>(moves)] = static_cast<Int32>(1024.0 * (quietBase + lnDepth * lnMoves / quietDivisor));
        }
    }
}

TUNABLE(LMR_FDEPTH_TT_PV_SCALE, 726, 0, 0, 0);

static inline MultiArray<Int32, 2, 256> LMP_TABLE;

namespace LMP {

static void init();

}

TUNABLE_CALLBACK(LMP_TABLE_BASE, 3, 0, 0, 0, []() { LMP::init(); })

static inline void LMP::init() {
    LMP_TABLE.fill({});

    for (Int32 improving = 0; improving < 2; improving++) {
        for (Int32 depth = 0; depth < 256; depth++) {
            LMP_TABLE[static_cast<USize>(improving)][static_cast<USize>(depth)] = (LMP_TABLE_BASE + depth * depth) / (2 - improving);
        }
    }
}

TUNABLE(LMP_MARGIN_HISTORY_SCALE, 527, 0, 0, 0);

TUNABLE(QUIET_HISTORY_PRUNING_MAX_FDEPTH, 640, 0, 0, 0);
TUNABLE(QUIET_HISTORY_PRUNING_MARGIN_DEPTH_SCALE, -2242, 0, 0, 0);
TUNABLE(QUIET_HISTORY_PRUNING_MARGIN_OFFSET, -1315, 0, 0, 0);

TUNABLE(QUIET_FP_MARGIN_BASE, 274, 0, 0, 0);
TUNABLE(QUIET_FP_MARGIN_DEPTH_SCALE, 68, 0, 0, 0);
TUNABLE(QUIET_FP_MARGIN_HISTORY_DIVISOR, 102, 0, 0, 0);
TUNABLE(QUIET_FP_MAX_FDEPTH, 1024, 0, 0, 0);

TUNABLE(NOISY_HISTORY_PRUNING_MAX_FDEPTH, 512, 0, 0, 0);
TUNABLE(NOISY_HISTORY_PRUNING_MARGIN_DEPTH_SCALE, -1006, 0, 0, 0);
TUNABLE(NOISY_HISTORY_PRUNING_MARGIN_OFFSET, -1121, 0, 0, 0);

TUNABLE(BNFP_MARGIN_BASE, 292, 0, 0, 0);
TUNABLE(BNFP_MARGIN_DEPTH_SCALE, 71, 0, 0, 0);
TUNABLE(BNFP_MARGIN_HISTORY_DIVISOR, 100, 0, 0, 0);
TUNABLE(BNFP_MAX_FDEPTH, 1024, 0, 0, 0);

TUNABLE(CAPTURE_FP_MARGIN_BASE, 383, 0, 0, 0);
TUNABLE(CAPTURE_FP_MARGIN_DEPTH_SCALE, 345, 0, 0, 0);
TUNABLE(CAPTURE_FP_MAX_FDEPTH, 896, 0, 0, 0);

TUNABLE(SEE_PRUNING_MARGIN_QUIET_DEPTH_SCALE, -20, 0, 0, 0);
TUNABLE(SEE_PRUNING_MARGIN_NOISY_DEPTH_SCALE, -111, 0, 0, 0);
TUNABLE(SEE_PRUNING_MARGIN_NOISY_HISTORY_DIVISOR, 65, 0, 0, 0);

TUNABLE(SE_MIN_FDEPTH_BASE, 640, 0, 0, 0);
TUNABLE(SE_MIN_FDEPTH_TT_PV_SCALE, 128, 0, 0, 0);
TUNABLE(SE_TT_FDEPTH_OFFSET, 348, 0, 0, 0);
TUNABLE(SE_BETA_MARGIN_BASE, 93, 0, 0, 0);
TUNABLE(SE_BETA_MARGIN_PREV_PV_SCALE, 93, 0, 0, 0);
TUNABLE(SE_DOUBLE_FEXT_MARGIN_BASE, 13, 0, 0, 0);
TUNABLE(SE_DOUBLE_FEXT_MARGIN_PV_SCALE, 135, 0, 0, 0);
TUNABLE(SE_DOUBLE_FEXT_MARGIN_NEW_PV_SCALE, 50, 0, 0, 0);
TUNABLE(SE_DOUBLE_FEXT_MARGIN_COMPLEXITY_SCALE, 881, 0, 0, 0);
TUNABLE(SE_TRIPLE_FEXT_MARGIN_BASE, 99, 0, 0, 0);
TUNABLE(SE_TRIPLE_FEXT_MARGIN_PV_SCALE, 375, 0, 0, 0);
TUNABLE(SE_TRIPLE_FEXT_MARGIN_NEW_PV_SCALE, 50, 0, 0, 0);
TUNABLE(SE_TRIPLE_FEXT_MARGIN_NOISY_TT_MOVE_SCALE, 199, 0, 0, 0);
TUNABLE(SE_TRIPLE_FEXT_MARGIN_COMPLEXITY_SCALE, 1014, 0, 0, 0);
TUNABLE(SE_QUADRUPLE_FEXT_MARGIN_BASE, 200, 0, 0, 0);
TUNABLE(SE_QUADRUPLE_FEXT_MARGIN_PV_SCALE, 500, 0, 0, 0);
TUNABLE(SE_QUADRUPLE_FEXT_MARGIN_NEW_PV_SCALE, 75, 0, 0, 0);
TUNABLE(SE_QUADRUPLE_FEXT_MARGIN_NOISY_TT_MOVE_SCALE, 300, 0, 0, 0);
TUNABLE(SE_QUADRUPLE_FEXT_MARGIN_COMPLEXITY_SCALE, 1200, 0, 0, 0);
TUNABLE(SE_SINGLE_FEXTENSION, 194, 0, 0, 0);
TUNABLE(SE_DOUBLE_FEXTENSION, 138, 0, 0, 0);
TUNABLE(SE_TRIPLE_FEXTENSION, 82, 0, 0, 0);
TUNABLE(SE_QUADRUPLE_FEXTENSION, 64, 0, 0, 0);
TUNABLE(SE_FAIL_HIGH_NEG_FEXTENSION, 384, 0, 0, 0);
TUNABLE(SE_CUT_NODE_NEG_FEXTENSION, 256, 0, 0, 0);
TUNABLE(SE_SCORE_NEG_FEXTENSION, 64, 0, 0, 0);
TUNABLE(SE_FAIL_LOW_NEG_FEXTENSION, 64, 0, 0, 0);

TUNABLE(MLDE_MAX_FDEPTH, 1280, 0, 0, 0);
TUNABLE(MLDE_MARGIN, 13, 0, 0, 0);
TUNABLE(MLDE_FEXTENSION, 64, 0, 0, 0);

TUNABLE(LDSE_MAX_FDEPTH, 896, 0, 0, 0);
TUNABLE(LDSE_SINGLE_FEXT_MARGIN, 22, 0, 0, 0);
TUNABLE(LDSE_DOUBLE_FEXT_MARGIN, 39, 0, 0, 0);
TUNABLE(LDSE_DOUBLE_FEXT_TT_FDEPTH_OFFSET, 348, 0, 0, 0);
TUNABLE(LDSE_SINGLE_FEXTENSION, 126, 0, 0, 0);
TUNABLE(LDSE_DOUBLE_FEXTENSION, 128, 0, 0, 0);

TUNABLE(MULTICUT_FAIL_FIRM_T, 503, 0, 0, 0);

static constexpr Int32 LMR_MIN_MOVES = 2;

TUNABLE(LMR_MIN_FDEPTH, 256, 0, 0, 0);
TUNABLE(LMR_FRED_OFFSET, -37, 0, 0, 0);
TUNABLE(LMR_FRED_QUIET_HISTORY_SCALE, 447, 0, 0, 0);
TUNABLE(LMR_FRED_NOISY_HISTORY_SCALE, 423, 0, 0, 0);
TUNABLE(LMR_FRED_NON_PV_SCALE, 1069, 0, 0, 0);
TUNABLE(LMR_FRED_TT_PV_SCALE, 1146, 0, 0, 0);
TUNABLE(LMR_FRED_IMPROVING_SCALE, 1242, 0, 0, 0);
TUNABLE(LMR_FRED_GIVES_CHECK_SCALE, 852, 0, 0, 0);
TUNABLE(LMR_FRED_CUT_NODE_SCALE, 1945, 0, 0, 0);
TUNABLE(LMR_FRED_TT_PV_FAIL_LOW_SCALE, 1054, 0, 0, 0);
TUNABLE(LMR_FRED_ALPHA_RAISES_SCALE, 597, 0, 0, 0);
TUNABLE(LMR_FRED_NOISY_TT_MOVE_SCALE, 1081, 0, 0, 0);
TUNABLE(LMR_FRED_MOVES_TRIED_SCALE, 42, 0, 0, 0);
TUNABLE(LMR_FRED_COMPLEXITY_SCALE, 480, 0, 0, 0);

TUNABLE(DEEPER_SEARCH_MARGIN_BASE, 40, 0, 0, 0);
TUNABLE(DEEPER_SEARCH_MARGIN_DEPTH_SCALE, 6, 0, 0, 0);
TUNABLE(DEEPER_SEARCH_FEXTENSION, 157, 0, 0, 0);

TUNABLE(SHALLOWER_SEARCH_MARGIN_BASE, 0, 0, 0, 0);
TUNABLE(SHALLOWER_SEARCH_MARGIN_DEPTH_SCALE, 1, 0, 0, 0);
TUNABLE(SHALLOWER_SEARCH_FREDUCTION, 135, 0, 0, 0);

TUNABLE(PCM_WEIGHT_BASE, 260, 0, 0, 0);
TUNABLE(PCM_WEIGHT_DEPTH_SCALE, 401, 0, 0, 0);
TUNABLE(PCM_WEIGHT_DEPTH_MAX, 4018, 0, 0, 0);
TUNABLE(PCM_WEIGHT_PREV_MOVES_TRIED_SCALE, 976, 0, 0, 0);
TUNABLE(PCM_WEIGHT_PREV_MOVES_TRIED_MIN, 8, 0, 0, 0);
TUNABLE(PCM_WEIGHT_PREV_TT_MOVE_SCALE, 948, 0, 0, 0);
TUNABLE(PCM_WEIGHT_STATIC_EVAL_SCALE, 1047, 0, 0, 0);
TUNABLE(PCM_WEIGHT_PREV_STATIC_EVAL_SCALE, 1023, 0, 0, 0);
TUNABLE(PCM_WEIGHT_MARGIN, 127, 0, 0, 0);
TUNABLE(PCM_WEIGHT_PREV_MARGIN, 131, 0, 0, 0);

TUNABLE(QSEARCH_FAIL_FIRM_T, 610, 0, 0, 0);
TUNABLE(QSEARCH_FP_MARGIN, 142, 0, 0, 0);
TUNABLE(QSEARCH_SEE_PRUNING_MARGIN, -81, 0, 0, 0);

static constexpr Int32 QSEARCH_MAX_MOVES = 2;

inline void TunableList::init() noexcept {
    MVV::init();
    SEE::init();
    LMR::init();
    LMP::init();
}

}
